language: node_js
node_js:
  - node
cache: yarn

before_install:
  - curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
  - sudo apt-get install apt-transport-https --yes
  - echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
  - sudo apt-get update
  - sudo apt-get install helm


script:
  - ./bin/run --version
  - ./bin/run --help
  - yarn test

after_success:
  - ./node_modules/.bin/nyc report --reporter text-lcov > coverage.lcov
  - bash < (curl -s https://codecov.io/bash)
